@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

SHOW_PERSON_PORTRAIT()
LAYOUT_LEFT_RIGHT()

Person(client, "Client", "Client que ira realizar a requisição HTTP para a API")

@enduml
